// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAQ1GnyEJp2IkRgH2oH5O-MsvFU2tXzYI',
    appId: '1:242679736794:web:19358faa1a7dd473b338e3',
    messagingSenderId: '242679736794',
    projectId: 'beatterapp',
    authDomain: 'beatterapp.firebaseapp.com',
    storageBucket: 'beatterapp.firebasestorage.app',
    measurementId: 'G-4S9GEH8E9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaSv2YV5AZY9OHQjmCJifljPzVeQo0FCU',
    appId: '1:242679736794:android:f1bf90daecd68085b338e3',
    messagingSenderId: '242679736794',
    projectId: 'beatterapp',
    storageBucket: 'beatterapp.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBldfTO5qolomI_SlzEpzdR3ZuibK6BIWs',
    appId: '1:242679736794:ios:dd3984c03655eac9b338e3',
    messagingSenderId: '242679736794',
    projectId: 'beatterapp',
    storageBucket: 'beatterapp.firebasestorage.app',
    iosClientId: '242679736794-1k1fbj59dcdugsuub10288gr7vksm51s.apps.googleusercontent.com',
    iosBundleId: 'com.nectares.beatter',
  );
}
